services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4000:3000"
    volumes:
      - ./frontend/pages:/app/pages
      - ./frontend/styles:/app/styles
      - ./frontend/public:/app/public
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8010:8010"
    volumes:
      - ./backend:/app # Ensure this matches your Dockerfile's WORKDIR
    env_file:
      - ./.env.development
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=next
    ports:
      - "5432:5432"

volumes:
  postgres_data:
