services:
  mySQL:
    image: mysql:latest
    restart: always
    container_name: mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./assets/init.sql:/docker-entrypoint-initdb.d/init.sql
